"""Crear tabla de proyectos

Revision ID: 111376bef8c3
Revises: fdfdf552f920
Create Date: 2025-05-28 13:10:04.713658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # Importante para JSONB y ARRAY


# revision identifiers, used by Alembic.
revision: str = '111376bef8c3'
down_revision: Union[str, None] = 'fdfdf552f920' # Reemplaza con el ID de la revisión de la tabla 'articles'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('projectsAndresPage',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True, index=True, autoincrement=True),
        sa.Column('slug', sa.String(length=255), unique=True, nullable=False, index=True),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True), # Descripción corta para la tarjeta/preview
        sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True), # Contenido detallado (array de ContentBlock)
        
        sa.Column('category', sa.String(length=100), nullable=True, index=True),
        sa.Column('author', sa.String(length=150), nullable=True), # Si es un proyecto personal
        
        sa.Column('status', sa.String(length=50), nullable=False), # Ej: 'Completado', 'En Progreso', 'Idea'
        sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('duration_text', sa.String(length=100), nullable=True), # Para "Aprox. 6 meses" o similar
        sa.Column('display_date', sa.String(length=100), nullable=True), # Fecha formateada para mostrar

        sa.Column('image_url', sa.Text(), nullable=True), # Imagen para la tarjeta de proyecto
        sa.Column('hero_image_url', sa.Text(), nullable=True), # Imagen principal para la página de detalle
        sa.Column('hero_image_alt', sa.Text(), nullable=True),
        
        sa.Column('project_url', sa.Text(), nullable=True), # Enlace al demo o sitio en vivo
        sa.Column('repository_url', sa.Text(), nullable=True), # Enlace al repositorio (GitHub, etc.)
        
        sa.Column('technologies_used', postgresql.ARRAY(sa.Text()), nullable=True),
        
        # Columna para las recomendaciones en formato JSONB, igual que en articles
        sa.Column('recommendation_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        
        sa.Column('priority', sa.Integer(), nullable=True, server_default='100', index=True),

        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###