"""Crear tabla de comentarios

Revision ID: 6b9a92f0be62
Revises: 111376bef8c3
Create Date: 2025-05-28 16:51:29.174989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b9a92f0be62'
down_revision: Union[str, None] = '111376bef8c3' # Reemplaza con el ID de la revisión de la tabla 'projects'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('comments',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True, index=True, autoincrement=True),
        sa.Column('parent_type', sa.String(length=50), nullable=False, index=True), # 'blog' o 'project'
        sa.Column('parent_slug', sa.String(length=255), nullable=False, index=True), # Slug del artículo o proyecto
        sa.Column('author_name', sa.String(length=150), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('avatar_color', sa.String(length=20), nullable=True), # Para el color del avatar generado en frontend
        sa.Column('is_approved', sa.Boolean(), nullable=False, server_default=sa.true()), # Para moderación básica, por defecto aprobados
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False)
    )
    # Índice para buscar comentarios por parent_type, parent_slug, y ordenarlos por fecha
    op.create_index(
        'ix_comments_parent_type_slug_created_at', 
        'comments', 
        ['parent_type', 'parent_slug', 'created_at'], 
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comments_parent_type_slug_created_at', table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###