"""Crear tabla daily_learning_content para preguntas, respuestas y datos curiosos

Revision ID: 94b4068ce8b7
Revises: d8ada87cf311
Create Date: 2025-05-27 18:55:30.207291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94b4068ce8b7'
down_revision: Union[str, None] = 'd8ada87cf311' # Reemplaza con tu revisión anterior real
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_learning_content',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True, index=True),
        sa.Column('question', sa.Text(), nullable=False),
        sa.Column('answer', sa.Text(), nullable=False),
        sa.Column('fun_fact', sa.Text(), nullable=False),
        sa.Column('category', sa.String(length=100), nullable=False, index=True),
        sa.Column('icon_name', sa.String(length=50), nullable=True),
        sa.Column('color_hex', sa.String(length=7), nullable=True), # Ej: #RRGGBB
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_learning_content')
    # ### end Alembic commands ###