"""Crear tabla de articulos

Revision ID: fdfdf552f920
Revises: 9d9c34766476
Create Date: 2025-05-27 21:45:54.631696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # Importante para JSONB y ARRAY


# revision identifiers, used by Alembic.
revision: str = 'fdfdf552f920'
down_revision: Union[str, None] = '9d9c34766476' # Asegúrate que este sea tu ID de revisión anterior correcto
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles_andres_page',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True, index=True, autoincrement=True),
        sa.Column('slug', sa.String(length=255), unique=True, nullable=False, index=True),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('summary', sa.Text(), nullable=True), # Corresponde a 'summary' de BlogPost
        sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False), # Para ContentBlock[]
        sa.Column('category', sa.String(length=100), nullable=True, index=True),
        sa.Column('author', sa.String(length=150), nullable=True),
        sa.Column('published_date', sa.DateTime(timezone=True), nullable=False), # Corresponde a publishedDate
        sa.Column('reading_time_minutes', sa.Integer(), nullable=True), # Corresponde a readingTimeMinutes
        sa.Column('hero_image_url', sa.Text(), nullable=True),
        sa.Column('hero_image_alt', sa.Text(), nullable=True), # Añadido por completitud
        sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
        
        # Campos adicionales para SEO y funcionalidad, basados en tu ejemplo de `Article` y buenas prácticas
        sa.Column('meta_description', sa.Text(), nullable=True),
        sa.Column('keywords', postgresql.ARRAY(sa.Text()), nullable=True), # Similar a tags, pero puede ser más para SEO
        
        # Nueva columna para las recomendaciones en formato JSONB
        # Almacenará un array de objetos, ej: [{"title": "...", "url": "...", "description": "...", "icon_name": "FaBook"}]
        sa.Column('recommendation_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        
        sa.Column('priority', sa.Integer(), nullable=True, server_default='100', index=True), # Para ordenar o destacar

        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    # ### end Alembic commands ###